# Generated by Django 4.2.7 on 2024-01-23 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0003_photo_user_alter_photo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_standard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
