# Generated by Django 5.0 on 2024-02-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_photo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('optimized', 'Optimized'), ('locked', 'Locked')], default='new', max_length=10),
        ),
    ]
