# Generated by Django 4.2.7 on 2024-03-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_photo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='copyright',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
