# Generated by Django 4.2.7 on 2024-03-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_alter_photo_copyright'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='source',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
