# Generated by Django 4.2.7 on 2024-03-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_alter_photo_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('optimized', 'Optimized'), ('locked', 'Locked'), ('standard', 'Standard')], default='new', max_length=10),
        ),
    ]
